<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    <style>
        #content, #page {
            width: 100%;
            margin: 0;
            float: none;
        }

        @page {
            margin: 2cm;
        }

        body {
            font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
            font-size: 13px;
            background: #fff !important;
            color: #000;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table th, table td {
            border: 1px solid #000;
            border-collapse: collapse;
            padding: 3px 5px;
            margin: 0px;
        }

    </style>
    @yield('styles')
</head>
<body>
<div id="page">
    <div id="content">
        <small>Report generated by Microloan - A solution by MyBooking Web Solution. - Generated at {{ date('Y-m-d H:i:s') }}</small>
        @yield('content')
    </div>
</div>

@yield('scripts')
</body>
</html>
